# # Default values for takemeout.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.
nameSpace: staging

app:
  name: take-me-out-back
  pod_http_port: 3000
  pod_metrics_port: 3001 
  service_port: 3000
  service_target_port: 3000
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m


database:
  name: database
  image: postgres:14
  port: 5432
