---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: takemeout
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: orwah/takemeout
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/orwah16/TakeMeOutBackGitOps.git
    targetRevision: main
    path: takemeout-chart
    # helm:
    #   parameters:
    #     - name: "replicaCount"
    #       value: "2"
    #     - name: "image.repository"
    #       value: aputra/nginx-lesson159
    #     - name: "image.tag"
    #       value: v0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true