
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: take-me-out-back-service
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: {{ .Values.app.service_port }}
      targetPort: {{ .Values.app.service_target_port }}
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: take-me-out-back-config
#   namespace: {{ .Values.nameSpace }}
#   labels:
#     app: take-me-out-back
# data:
#   PGDATABASE: "takemeoutdb"
#   PGHOST: "db"
#   PGPASSWORD: "123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: app
          image: orwah/takemeout:a25c49974ccab23354de89d381cf43551bf941bf
          # volumeMounts:
          #   - name: node-persistent-storage
          #     mountPath: /data/db
          ports:
            - name: http
              containerPort:  {{ .Values.app.pod_http_port }}
            - name: http-metrics
              containerPort:  {{ .Values.app.pod_metrics_port }}
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m
          env:
            - name: PGDATABASE
              value: takemeoutdb
            - name: PGHOST
              value: database
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: "123456"


          imagePullPolicy: Always 
      # volumes:
      #   - name: mongo-persistent-storage
      #     awsElasticBlockStore:
      #       volumeID: aws://{region}/{volume ID}
      #       fsType: ext4